ignore:
  - vulnerability: CVE-2023-39325
    package:
      name: stdlib
      version: go1.21.0
  - vulnerability: CVE-2023-45288
    package:
      name: stdlib
      version: go1.21.0
  - vulnerability: GHSA-rcjv-mgp8-qvmr
    package:
      name: go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin
  - vulnerability: GHSA-2c4m-59x9-fr2g
    package:
      name: github.com/gin-gonic/gin
  - vulnerability: GHSA-3vp4-m3rf-835h
    package:
      name: github.com/gin-gonic/gin
  - vulnerability: GHSA-hcg3-q754-cr77
    package:
      name: golang.org/x/crypto
  - vulnerability: GHSA-vvgc-356p-c3xw
    package:
      name: golang.org/x/net
  - vulnerability: GHSA-qxp5-gwg8-xv66
    package:
      name: golang.org/x/net
  - vulnerability: CVE-2023-39325
    package:
      name: stdlib
      version: go1.21.0
  - vulnerability: CVE-2023-39232
    package:
      name: stdlib
      version: go1.21.0
  - vulnerability: CVE-2023-45283
    package:
      name: stdlib
      version: go1.21.0
  - vulnerability: CVE-2023-44487
    package:
      name: stdlib
      version: go1.21.0
  - vulnerability: CVE-2023-45288
    package:
      name: stdlib
      version: go1.21.0
